server:
  port: ${PORT:8086}

spring:
  datasource:
    url: ${DB_URL:jdbc:postgresql://localhost:5432/shopery_db}
    username: ${DB_USERNAME:shopery_user}
    password: ${DB_PASSWORD:shopery_pass}

  jpa:
    show-sql: true
    properties:
      hibernate:
        format_sql: true

feign:
  client:
    config:
      order-ms:
        url: ${ORDER_MS:http://localhost:8087}
