server:
  port: ${PORT:8086}

spring:
  datasource:
    url: ${DB_URL}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}

  jpa:
    show-sql: false
    properties:
      hibernate:
        format_sql: false

feign:
  client:
    config:
      order-ms:
        url: ${ORDER_MS}
